"""2026 課堂題：陳顧中老師 Ch23 slides 上的「課後練習題」（多為國考題，答案依 slides 標示）。
用法：python3 tools/biochem/class_questions.py → subjects/biochem/data/questions-class.json
每題：(章節, 考點, 題幹, [選項A..D], 答案, 詳解, slides 頁碼)
"""
import json, os
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'subjects', 'biochem', 'data', 'questions-class.json')

Q = [
 ('ch23', ['各器官燃料代謝'], '身體中持續存在燃料（fuel）可維持熱量恆定（caloric homeostasis），燃料使用的優先順序為下列何者？（112-1 牙醫師）',
  ['肝醣 > 蛋白質 > 三酸甘油脂', '三酸甘油脂 > 肝醣 > 蛋白質', '三酸甘油脂 > 蛋白質 > 肝醣', '肝醣 > 三酸甘油脂 > 蛋白質'], 'D',
  '先用肝醣（約一天內用完），再動用脂肪（TG → 脂肪酸、酮體），蛋白質是最後手段（長期飢餓才大量分解肌肉蛋白）。', 5),
 ('ch23', ['各器官燃料代謝'], '肌肉細胞因缺乏下列何種酵素，而無法釋出葡萄糖於血液中？（115-1 保健）',
  ['Fumarase', 'Glucose-6-phosphatase', 'Hexokinase', 'Pyruvate dehydrogenase'], 'B',
  '肌肉沒有 glucose-6-phosphatase，肝醣分解產生的 G6P 只能自己進糖解，不能變成游離葡萄糖送進血液。只有肝（和腎）能。', 10),
 ('ch23', ['各器官燃料代謝'], '肝臟是調整血糖的重要器官，當空腹時，肝醣轉換成葡萄糖過程中，需要下列何種酵素參與反應？（113-2 技）',
  ['Glucose oxidase', 'Glycogen synthase', 'Hexokinase', 'Glucose-6-phosphatase'], 'D',
  '肝醣 →（glycogen phosphorylase）G1P → G6P →（glucose-6-phosphatase）葡萄糖釋入血液。', 10),
 ('ch23', ['各器官燃料代謝'], '肌肉中因缺乏何種酵素，故肌肉中的肝醣無法轉變成為葡萄糖？（112-2 醫檢師、113-1 營養師）',
  ['Glucokinase', 'Phosphorylase a', 'Hexokinase', 'Glucose-6-phosphatase'], 'D',
  '同上：肌肉缺 glucose-6-phosphatase，肝醣只供肌肉自己用。', 10),
 ('ch23', ['各器官燃料代謝'], '下列何者不是維持血糖的途徑？（113-1 營養師）',
  ['由飲食中吸收的糖類', '半乳糖、果糖在肝中轉變成葡萄糖', '肌肉中肝醣分解', '糖質新生作用'], 'C',
  '肌肉肝醣分解只產生 G6P 供肌肉自用（缺 glucose-6-phosphatase），不能補充血糖。', 10),
 ('ch23', ['Cori／葡萄糖-丙胺酸循環'], '無氧代謝時，將一莫耳（mole）的葡萄糖經由糖解作用（glycolysis）及酵素 lactate dehydrogenase 轉化成兩莫耳的乳酸（lactate），最終淨產生：（113-1 醫師）',
  ['一莫耳的 ATP', '兩莫耳的 ATP', '一莫耳的 ATP 以及兩莫耳的 NADH', '兩莫耳的 ATP 以及兩莫耳的 NADH'], 'B',
  '糖解淨得 2 ATP + 2 NADH；但 2 NADH 被 LDH 用來把 pyruvate 還原成 lactate（再生 NAD⁺），所以淨產物只剩 2 ATP。', 12),
 ('ch23', ['Cori／葡萄糖-丙胺酸循環'], '瓦氏效應（Warburg effect）是指下列那一種葡萄糖代謝途徑，其主要為癌細胞所利用？（115-2 醫檢師）',
  ['葡萄糖代謝成乳酸（lactic acid）', '葡萄糖代謝成乙醇（ethanol）', '葡萄糖代謝成乙醯輔酶A（acetyl-CoA）', '葡萄糖代謝成NADH'], 'A',
  'Warburg effect＝有氧糖解（aerobic glycolysis）：即使有氧氣，癌細胞仍大量把葡萄糖代謝成乳酸，以快速取得 ATP 與合成原料。', 16),
 ('ch23', ['Cori／葡萄糖-丙胺酸循環'], '下列那一個反應有助於利用乳酸以維持血液中葡萄糖的含量？（113-2 技）',
  ['肝醣分解（glycogenolysis）', '糖解作用（glycolysis）', '糖質新生（gluconeogenesis）', '乳酸發酵作用（lactate fermentation）'], 'C',
  'Cori cycle：肌肉的乳酸送到肝，肝經 gluconeogenesis 把乳酸變回葡萄糖。', 16),
 ('ch23', ['Cori／葡萄糖-丙胺酸循環'], '下列關於 Cori cycle 在體內不同組織進行反應的敘述，何者正確？（111-1 醫學）',
  ['乳酸（lactate）由肝臟運送到骨骼肌', '葡萄糖由骨骼肌運送到肝臟', '肝臟經過糖質新生（gluconeogenesis）產生葡萄糖', '骨骼肌經過糖質新生（gluconeogenesis）產生乳酸'], 'C',
  '方向：肌肉（糖解 → 乳酸）→ 血液 → 肝（糖質新生 → 葡萄糖）→ 血液 → 肌肉。肝花 6 ATP、肌肉得 2 ATP。', 16),
 ('ch23', ['各器官燃料代謝'], '短跑選手在起跑數秒內的急速爆發是依賴肌肉中的何種物質再生 ATP？（111-2 營養師）',
  ['磷酸肌酸（creatine phosphate）', '脂肪酸 β 氧化（fatty acid β-oxidation）', '肝醣分解（glycogenolysis）', '厭氧糖解（anaerobic glycolysis）'], 'A',
  'Phosphocreatine + ADP →（creatine kinase）→ creatine + ATP，最快的 ATP 緩衝，只夠撐幾秒；之後才是無氧糖解、再來是有氧代謝。', 22),
 ('ch23', ['各器官燃料代謝'], '有關肌酸（creatine）、肌酸酐（creatinine）、磷酸肌酸（phosphocreatine），下列敘述何者錯誤？（111-1 醫檢）',
  ['creatine 的生合成可在腎臟中進行', 'creatine 經脫水反應形成 creatinine', 'creatine 經 creatininase 作用產生 phosphocreatine', 'phosphocreatine 轉變成 creatinine 反應不需酵素催化'], 'C',
  'Creatine 磷酸化成 phosphocreatine 靠的是 creatine kinase（不是 creatininase）。Creatine／phosphocreatine 會非酵素性脫水環化成 creatinine，經尿液排出（腎功能指標）。Creatine 由 arginine + glycine 在腎開始合成，在肝由 SAM 甲基化完成。', 22),
 ('ch23', ['各器官燃料代謝'], '長期高量葡萄糖或果糖攝取，會導致肝臟何種脂質的堆積，造成非酒精性脂肪肝的生成？（113-2 保）',
  ['蠟脂', '磷脂質', '三酸甘油酯', '肌醇三磷酸'], 'C',
  '過量的醣在肝轉成 acetyl-CoA → 脂肪酸 → 三酸甘油酯（TG），若輸出（VLDL）不及就堆積成脂肪肝。', 24),
 ('ch23', ['酮體'], '有關血中酮體（ketone body）的敘述，下列何者最不適當？（115-2 醫檢師）',
  ['丙酮（acetone）可由呼吸排出體外', '乙醯輔酶A（acetyl-CoA）為酮體合成起始物', 'β-羥基丁酸（β-hydroxybutyrate）為最早生成的酮體', 'β-羥基丁酸（β-hydroxybutyrate）為濃度最高的酮體'], 'C',
  '最早生成的酮體是 acetoacetate（HMG-CoA lyase 的產物），再由 β-hydroxybutyrate dehydrogenase 用 NADH 還原成 β-hydroxybutyrate；acetone 由 acetoacetate 自發脫羧，經呼吸排出。', 30),
 ('ch23', ['酮體'], '有關人體合成及利用 ketone bodies 的敘述，下列何者正確？（114-2 營養師）',
  ['肝臟細胞的細胞質為合成酮體的場所，所產生酮體再運送至肝外組織作能量來源', '酮體合成材料是 acetyl-CoA 和 malonyl-CoA，生成的中間產物為 3-hydroxy-3-methylglutaryl-CoA（HMG-CoA）', '人體產生的酮體包括 acetone、acetoacetate、β-hydroxylmethylbutyrate', '酮體運送至肝外組織後會分解為 acetyl-CoA 而進入檸檬酸循環'], 'D',
  '(A) 酮體在肝的粒線體合成。(B) 原料只有 acetyl-CoA（malonyl-CoA 是脂肪酸合成的）。(C) 是 β-hydroxybutyrate，不是 β-hydroxymethylbutyrate。(D) 正確：肝外組織用 succinyl-CoA transferase（肝沒有）把 acetoacetate 變回 acetyl-CoA 進 TCA。', 30),
 ('ch23', ['酮體'], '下列何者是造成酮酸血症最主要的酮體？（114-2 醫檢）',
  ['α-ketoglutarate', 'acetoacetic acid', 'β-hydroxybutyric acid', 'acetone'], 'C',
  '血中濃度最高的酮體是 β-hydroxybutyrate，是酮酸血症的主角；acetone 不是酸。', 30),
 ('ch23', ['酮體'], '下列那兩種酮體（ketone body）在健康人血液內，其濃度幾乎相同？（114-1 醫檢師）',
  ['丙酮（acetone）與乙醯乙酸（acetoacetate）', '乙醯乙酸（acetoacetate）與β-羥基丁酸（β-hydroxybutyrate）', '丙酮（acetone）與β-羥基丁酸（β-hydroxybutyrate）', 'β-羥基丁酸（β-hydroxybutyrate）與醋酸（acetate）'], 'B',
  '健康人 acetoacetate 與 β-hydroxybutyrate 約 1:1；飢餓或糖尿病時 NADH/NAD⁺ 上升，β-hydroxybutyrate 比例大增。', 30),
 ('ch23', ['酮體'], '在生化的轉換過程中，如果乙醯輔酶A（acetyl-CoA）過量，會尋求可行路徑形成酮體（ketone body），下列何者不屬於此類酮體分子？（114-1 醫檢師）',
  ['乙醯乙酸（acetoacetic acid）', 'β-羥基丁酸（β-hydroxybutyric acid）', '丙酮（acetone）', '乙醯丙酮（acetylacetone）'], 'D',
  '三種酮體：acetoacetate、β-hydroxybutyrate、acetone。', 31),
 ('ch23', ['各器官燃料代謝'], '下列何者不是肝臟的生理功能？（114-1 牙醫師）',
  ['產生胰島素（insulin）以調節新陳代謝', '將胺基酸轉化為代謝燃料', '解毒（detoxification）', '糖質新生（gluconeogenesis）'], 'A',
  '胰島素由胰臟蘭氏小島 β 細胞分泌，不是肝臟。', 31),
 ('ch23', ['酮體'], '下列何者是酮體（ketone bodies）的成分？（113-2 牙）',
  ['acetyl CoA', 'β-hydroxybutyrate', 'malonyl CoA', 'melanonate'], 'B', '三種酮體：acetoacetate、β-hydroxybutyrate、acetone。', 31),
 ('ch23', ['酮體'], '酮體於肝臟合成後，會透過血液循環送至肝外組織，血液中的酮體主要型態為何？（113-2 保）',
  ['乙醯輔酶A（acetyl-CoA）', '乙醯乙酸（acetoacetate）', 'β-羥基丁酸（β-hydroxybutyric acid）', 'β-羥甲基丁酸（β-hydroxymethylbutyric acid）'], 'C',
  '血中主要型態是 β-hydroxybutyrate（共筆 Ch17 也考過同一題英文版）。', 31),
 ('ch23', ['酮體'], '關於酮體（ketone bodies）的敘述，下列何者錯誤？（113-1 牙醫師）',
  ['包括丙酮（acetone）、乙醯乙酸酯（acetoacetate）、β 羥基丁酸酯（β-hydroxybutyrate）', '主要在小腸細胞之粒線體中合成', '生合成涉及的酵素包括硫解酶（thiolase）、HMG-CoA 裂解酶（HMG-CoA lyase）和 HMG-CoA 合成酶（HMG-CoA synthase）', '為飢餓時大腦的主要能量來源'], 'B',
  '酮體在肝細胞的粒線體合成，不是小腸。', 32),
 ('ch23', ['酮體'], '下列何者與酮體（ketone body）過量產生的酸中毒（acidosis）無關？（112-2 醫檢師）',
  ['丙酮（acetone）', '乙醯乙酸（acetoacetate）', 'β-羥基丁酸（β-hydroxybutyrate）', '醋酸（acetate）'], 'AD',
  'Acetoacetate 與 β-hydroxybutyrate 是酸，造成酮酸中毒；acetone 是中性分子（經呼吸排出），acetate 也不是酮體。', 32,
  'slides 標「#」（國考公告送分）：acetone 和 acetate 都可以算「無關」，選 A 或 D 都算對。'),
 ('ch23', ['酮體'], '有關酮體（ketone bodies）的敘述，下列何者正確？（111-2 醫檢師）',
  ['acetyl-CoA 生成過多是酮體形成的主因', '正常人體內的酮體以 acetoacetate 居多', '食用澱粉類的食物較脂肪容易產生酮體', '臨床上常以 acetoacetate 作為定量的對象'], 'A',
  'Acetyl-CoA 過多（TCA 中間物被糖質新生抽走，OAA 不足）→ 轉向生酮。β-hydroxybutyrate 才是血中最多、也是臨床定量的主要對象；高脂低醣飲食才容易產生酮體。', 32),
 ('ch23', ['各器官燃料代謝'], '有關醣類代謝之敘述，下列何者錯誤？（115-2 營養師）',
  ['糖解作用（glycolysis）與糖質新生作用（gluconeogenesis）均可發生於肝臟細胞中', '1 分子葡萄糖經糖解作用可淨生成 4 分子 ATP 與 2 分子 NADH', '紅血球因缺少粒線體，需依賴糖解作用生成乳酸的途徑來獲取能量', '劇烈運動下，肌肉中的乳酸去氫酶（lactate dehydrogenase）可利用丙酮酸產生乳酸'], 'B',
  '糖解總共產生 4 ATP，但投資 2 ATP，淨得 2 ATP 與 2 NADH。', 35),
 ('ch23', ['各器官燃料代謝'], '下列何者為紅血球生成三磷酸腺苷（ATP）之最主要途徑？（115-1 保健）',
  ['糖解作用（glycolysis）', '克氏循環（Krebs cycle）', '氧化磷酸化（oxidative phosphorylation）', 'β-氧化作用（β-oxidation）'], 'A',
  '紅血球沒有粒線體，只能靠糖解（終產物乳酸）。', 35),
 ('ch23', ['各器官燃料代謝'], '人體於飲食攝取葡萄糖後的兩小時內，在各組織中的葡萄糖利用，下列何者錯誤？（114-2 營養師）',
  ['在腦部可被氧化而產生 ATP', '在紅血球可進入糖解作用', '在脂肪組織可成為合成三酸甘油酯的原料', '在肝臟優先進入脂肪酸合成途徑'], 'D',
  '飯後肝臟優先把葡萄糖合成肝醣（glycogen），肝醣存滿後多餘的才轉成脂肪酸。', 35),
 ('ch23', ['各器官燃料代謝'], '下列關於 glucose 在人類的紅血球中代謝的敘述，何者錯誤？（113-2 醫學）',
  ['Glucose 代謝最終產物之一為 lactic acid', 'Pyruvate 可轉化為 acetyl-CoA 進一步代謝', '提供 NADPH 使 glutathione 保持還原狀態', 'Glucose 也可以利用 pentose phosphate 途徑代謝'], 'B',
  '紅血球沒有粒線體，沒有 pyruvate dehydrogenase，pyruvate 只能變成 lactate。PPP 提供 NADPH 維持還原型 glutathione（G6PD 缺乏 → 溶血）。', 35),
 ('ch23', ['胰島素與 GLUT'], '有關胰島素功能之敘述，下列何者最不適當？（115-2 醫檢師）',
  ['刺激肝臟進行糖質新生作用', '促進醣類轉變成肝醣或脂肪進行儲存', '刺激蛋白質合成', '刺激肌肉細胞吸收葡萄糖進行能量利用'], 'A',
  '胰島素「促進合成、抑制分解」：抑制糖質新生（是升糖素和 cortisol 促進糖質新生）。', 41),
 ('ch21', ['膽固醇合成與 HMG-CoA reductase'], '哺乳動物體內生合成膽固醇（cholesterol）的關鍵酵素 HMG-CoA reductase 會受到多層面及多種因素的調控。下列何者可增加 HMG-CoA reductase 的酵素反應，進而促成膽固醇的生合成？（114-1 營養師）',
  ['升糖素（glucagon）', '胰島素（insulin）', '低 ATP 含量（low ATP levels）', '氧化固醇（oxysterol）'], 'B',
  'Insulin 使 HMG-CoA reductase 去磷酸化（活化）；glucagon 與 AMPK（低 ATP）使其磷酸化（抑制）；sterol（含 oxysterol）促進其泛素化降解、並抑制 SREBP。', 41),
 ('ch23', ['胰島素與 GLUT'], '下列何種荷爾蒙可促進脂質合成（lipogenesis）？（112-2 營養師）',
  ['腎上腺素（epinephrine）', '糖皮質素（glucocorticoids）', '生長激素（growth hormone）', '胰島素（insulin）'], 'D',
  '胰島素活化 ACC（去磷酸化）、促進脂肪酸與 TG 合成；其他三者偏向動員脂肪。', 41),
 ('ch12', ['RTK 與胰島素訊號'], '下列何者是直接透過 receptor tyrosine kinase 的活化來傳遞訊息？（115-1 牙醫）',
  ['Insulin', 'Serotonin', 'Epinephrine', 'Acetylcholine'], 'A',
  'Insulin receptor 是 RTK（α₂β₂ 四聚體，結合後 β 次單元自體磷酸化）。Epinephrine、多數 serotonin 受體走 GPCR；acetylcholine 的 nicotinic 受體是配體門控離子通道。', 44),
 ('ch12', ['GPCR 與 cAMP／PKA'], '下列何種訊息分子通常不會直接結合於 G protein-coupled receptor（GPCR）來進行訊息傳遞？（112-2 醫師）',
  ['Angiotensin', 'Prostaglandin', 'Epinephrine', 'Insulin'], 'D',
  'Insulin 結合 receptor tyrosine kinase；其他三者都透過 GPCR。', 44),
 ('ch23', ['胰島素與 GLUT'], '下列何者為胰島素調節的葡萄糖轉運體（glucose transporter）？（114-1 醫檢師）',
  ['GLUT1', 'GLUT2', 'GLUT3', 'GLUT4'], 'D',
  'GLUT4（骨骼肌、心肌、脂肪）平時存在細胞內囊泡，胰島素訊號（PI3K–Akt）使其移到細胞膜。', 47),
 ('ch23', ['胰島素與 GLUT'], '關於促進葡萄糖轉運子-5（facilitative glucose transporter-5, GLUT5）的敘述，下列何者正確？（112-1、113-2 技）',
  ['存在於血腦障壁（blood-brain-barrier）上幫助葡萄糖運送', '需胰島素（insulin）協助葡萄糖運送入細胞', '可將果糖送入腸道細胞內', '負責運送葡萄糖進入蘭氏小島 β cells'], 'C',
  'GLUT5 是果糖轉運體（小腸、精子）。血腦障壁＝GLUT1；胰島素依賴＝GLUT4；β 細胞＝GLUT2。', 47),
 ('ch23', ['胰島素與 GLUT'], '下列何種葡萄糖運輸蛋白（glucose transporter, GLUT）與腎臟細胞運輸尿酸鹽有關？（113-1 醫檢師）',
  ['GLUT1', 'GLUT3', 'GLUT5', 'GLUT9'], 'D', 'GLUT9（SLC2A9）在肝、腎運輸尿酸鹽（urate），與腎性低尿酸血症有關。', 47),
 ('ch23', ['胰島素與 GLUT'], '關於胰島素（insulin）訊息如何活化肝臟細胞的肝醣合成酶（glycogen synthase, GS）的活性，下列描述何者最合理？（114-2 醫學）',
  ['造成 GSK3 去磷酸化，提高 GSK3 激酶活性，活化 GS', '造成 GSK3 磷酸化，提高 GSK3 激酶活性，活化 GS', '造成 GSK3 去磷酸化，抑制 GSK3 激酶活性，活化 GS', '造成 GSK3 磷酸化，抑制 GSK3 激酶活性，活化 GS'], 'D',
  'Insulin → PI3K → Akt（PKB）把 GSK3 的 Ser 磷酸化 → GSK3 失活 → 不再磷酸化（抑制）glycogen synthase，加上 PP1 去磷酸化 → GS 活化。', 49),
 ('ch23', ['瘦素與脂肪激素'], '瘦體素（leptin）經由訊息傳遞後，會增加下列何種蛋白質的合成，進而導致產熱效應（thermogenesis）？（115-1 保健）',
  ['AMP-activated protein kinase（AMPK）', 'Uncoupling protein 1（UCP1）', 'Adenylyl cyclase', 'ATP synthase'], 'B',
  'Leptin → 下視丘 → 交感神經 norepinephrine → 脂肪細胞 β3-adrenergic receptor → cAMP/PKA → UCP1（thermogenin）表現 ↑ → 產熱。', 57),
 ('ch23', ['瘦素與脂肪激素'], '下列何種賀爾蒙是由脂肪組織所分泌，並具有降低食慾刺激代謝的功能？（112-1 醫檢師）',
  ['脂締素（adiponectin）', '瘦素（leptin）', '阻抗素（resistin）', '抑制素（inhibin）'], 'B',
  'Leptin（OB gene 產物）作用在下視丘 arcuate nucleus：抑制食慾（↓NPY/AgRP、↑POMC）、增加能量消耗。', 57),
]

out = []
for i, row in enumerate(Q, 1):
    ch, topics, stem, opts, ans, exp, page = row[:7]
    q = {'id': f'class-{i:03d}', 'source': '2026 課堂題', 'section': f'Ch23 slides p.{page}', 'chapter': ch, 'type': 'mcq',
         'stem': stem, 'options': [{'k': 'ABCD'[j], 't': t} for j, t in enumerate(opts)], 'answer': list(ans),
         'explain': exp, 'topics': topics,
         'pattern': '選錯誤（否定）題' if any(w in stem for w in ('錯誤', '不是', '不適當', '無關', '不屬於', '不會')) else '選正確／單一概念題'}
    if len(row) > 7: q['note'] = row[7]
    out.append(q)
json.dump(out, open(OUT, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print(len(out))
