"""模擬新題（依 2026 slides 與 113 共筆考點編寫）→ subjects/biochem/data/questions-new.json"""
import json, os
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'subjects', 'biochem', 'data', 'questions-new.json')
P1, P0, PM, PC = '選正確／單一概念題', '選錯誤（否定）題', '配對題', '臨床情境題'
# (chapter, topics, pattern, stem, [A,B,C,D], answer, explain)
Q = [
# ---------------- Ch12 ----------------
('ch12',['訊息傳遞特徵與受體類型'],P1,
 'The sensitivity of a signal-transduction system is determined mainly by:',
 ['The affinity (Kd) of the receptor for its signal molecule','The number of kinases in the cascade','The rate at which the hormone is secreted','The number of second messengers produced'],
 'A','Sensitivity 主要來自受體對訊號的高親和力（Kd 低）。課本也提到 cooperativity 與 cascade 放大會提高敏感度，但最根本的決定因素是受體親和力。'),
('ch12',['訊息傳遞特徵與受體類型'],P1,
 'Which of the following receptors is a ligand-gated ion channel?',
 ['β-adrenergic receptor','Nicotinic acetylcholine receptor','Insulin receptor','Estrogen receptor'],
 'B','Nicotinic ACh receptor 是配體門控通道；β-adrenergic 是 GPCR，insulin receptor 是 RTK，estrogen receptor 是核受體。'),
('ch12',['訊息傳遞特徵與受體類型'],PM,
 'Which pairing of receptor and receptor class is INCORRECT?',
 ['β-adrenergic receptor — G protein–coupled receptor','ANF receptor — receptor guanylyl cyclase','Glucocorticoid receptor — nuclear receptor','Insulin receptor — G protein–coupled receptor'],
 'D','Insulin receptor 是 receptor tyrosine kinase（受體酵素），不是 GPCR。'),
('ch12',['GPCR 與 cAMP／PKA'],P0,
 'Which statement about the stimulatory G protein (Gs) is FALSE?',
 ['In the resting state, Gsα has GDP bound','The activated receptor promotes exchange of GDP for GTP on Gsα','Gsα-GTP dissociates from βγ and activates adenylyl cyclase','Gsα is switched off when cAMP phosphodiesterase hydrolyzes its bound GTP'],
 'D','Gsα 靠自己內建的 GTPase 把 GTP 水解成 GDP 而關閉；cAMP phosphodiesterase 分解的是 cAMP。'),
('ch12',['GPCR 與 cAMP／PKA'],P1,
 'How many molecules of cAMP are required to release both catalytic subunits of one PKA holoenzyme (R2C2)?',
 ['1','2','4','8'],
 'C','每個 R 次單元結合 2 個 cAMP，兩個 R 共 4 個 → 釋出 2 個 C。所以 cAMP → PKA 這一步不放大。'),
('ch12',['GPCR 與 cAMP／PKA'],P1,
 'Desensitization of the β-adrenergic receptor during prolonged exposure to epinephrine involves:',
 ['Phosphorylation of the receptor by βARK followed by binding of β-arrestin','Phosphorylation of Gsα by protein kinase C','Activation of cGMP phosphodiesterase','Increased synthesis of the receptor'],
 'A','βARK（GRK2）磷酸化受體 C 端 → β-arrestin 結合 → 受體被內吞；之後去磷酸化再送回膜上。'),
('ch12',['GPCR 與 cAMP／PKA'],P1,
 'In liver cells, an inhibitor of cAMP phosphodiesterase (e.g., theophylline) would be expected to:',
 ['Prolong the stimulatory effect of glucagon or epinephrine on glycogen breakdown','Block activation of adenylyl cyclase','Decrease PKA activity','Inhibit the GTPase activity of Gsα'],
 'A','PDE 被抑制 → cAMP 分解變慢 → PKA 活化更久 → 肝醣分解持續。'),
('ch12',['IP3／DAG／Ca²⁺'],P1,
 'Hydrolysis of PIP2 by phospholipase C generates:',
 ['IP3, which activates protein kinase C, and DAG, which opens ER Ca²⁺ channels','IP3, which opens Ca²⁺ channels in the ER, and DAG, which together with Ca²⁺ activates protein kinase C','cAMP and cGMP','PIP3 and DAG'],
 'B','IP₃ 水溶、結合 ER 上的 Ca²⁺ 通道；DAG 留在膜上，與 Ca²⁺ 一起活化 PKC。常見陷阱是把兩者的作用對調。'),
('ch12',['cGMP／NO'],P1,
 'Sildenafil (Viagra) enhances smooth-muscle relaxation by:',
 ['Activating soluble guanylyl cyclase','Inhibiting cGMP-specific phosphodiesterase (PDE5)','Releasing nitric oxide','Blocking protein kinase G'],
 'B','抑制 PDE5 → cGMP 分解變慢 → PKG 活化更久 → 血管舒張。'),
('ch12',['cGMP／NO'],P0,
 'Which statement about nitric oxide (NO) signaling is FALSE?',
 ['NO is produced from arginine by NO synthase','NO activates a soluble, heme-containing guanylyl cyclase','NO is stable in blood and acts mainly on distant organs','The resulting cGMP activates protein kinase G and relaxes smooth muscle'],
 'C','NO 是氣體、半衰期很短，作用在鄰近細胞（局部反應）。'),
('ch12',['GPCR 與 cAMP／PKA'],P1,
 'In vertebrate rod cells, absorption of light by rhodopsin leads to:',
 ['Activation of adenylyl cyclase and a rise in cAMP','Activation of cGMP phosphodiesterase via transducin and a fall in cGMP','Opening of cGMP-gated Na⁺/Ca²⁺ channels','Release of IP3 from the disk membrane'],
 'B','光 → rhodopsin（GPCR）→ transducin → cGMP PDE 活化 → cGMP ↓ → 通道關閉、細胞過極化。'),
('ch12',['RTK 與胰島素訊號'],P0,
 'Which statement about the insulin receptor is FALSE?',
 ['It is an (αβ)2 dimer whose β subunits have tyrosine kinase activity','Insulin binding triggers autophosphorylation of Tyr residues in the β subunits','Phosphorylated IRS-1 recruits proteins containing SH2 domains','It activates Gs to raise intracellular cAMP'],
 'D','Insulin receptor 是 RTK，經 IRS-1 → PI3K／Ras 傳遞訊號，不經 Gs 和 cAMP。'),
('ch12',['RTK 與胰島素訊號'],P1,
 'Which sequence correctly describes the insulin-activated MAPK cascade?',
 ['Grb2 → Sos → Ras → Raf → MEK → ERK','Sos → Grb2 → Raf → Ras → ERK → MEK','Ras → Grb2 → Sos → MEK → Raf → ERK','Grb2 → Ras → Sos → ERK → MEK → Raf'],
 'A','Grb2（SH2）接上 IRS-1 → Sos（GEF）→ Ras-GTP → Raf（MAPKKK）→ MEK（MAPKK）→ ERK（MAPK）。'),
('ch12',['RTK 與胰島素訊號'],P1,
 'Insulin stimulates glycogen synthesis in muscle mainly because protein kinase B (Akt):',
 ['Phosphorylates and directly activates glycogen synthase','Phosphorylates and inactivates GSK3, so glycogen synthase remains dephosphorylated and active','Dephosphorylates GSK3','Activates glycogen phosphorylase'],
 'B','GSK3 平時磷酸化 glycogen synthase 使它失活；Akt 磷酸化 GSK3 → GSK3 失活 → GS 保持活化。'),
('ch12',['RTK 與胰島素訊號'],P1,
 'The PH (pleckstrin homology) domain of proteins such as Akt and PDK1 binds:',
 ['Phosphotyrosine','PIP3','Phospho-Ser/Thr','cAMP'],
 'B','PH domain 結合 PIP₃，把 Akt、PDK1 招到膜上；SH2、PTB 認得 pTyr；14-3-3 認得 pSer/Thr。'),
('ch12',['核受體與類固醇'],P1,
 'Tamoxifen is used to treat estrogen-dependent breast cancer because it:',
 ['Binds the estrogen receptor but fails to activate it','Blocks the progesterone receptor','Inhibits the BCR-ABL tyrosine kinase','Inhibits aromatase in the nucleus'],
 'A','Tamoxifen 與 estrogen 競爭 estrogen receptor 但不活化轉錄。阻斷 progesterone receptor 的是 RU486；BCR-ABL 是 Gleevec 的標的。'),
('ch12',['細胞週期與癌症'],P0,
 'Which statement about the G1/S checkpoint is FALSE?',
 ['CDK-dependent phosphorylation of pRb releases E2F','After DNA damage, p53 induces p21, which inhibits CDK2–cyclin E','Cyclin B–CDK1 is the main complex driving the G1→S transition','DNA damage activates the kinases ATM/ATR'],
 'C','G1/S 由 cyclin E–CDK2（與 cyclin D–CDK4/6）推動；cyclin B–CDK1 負責進入 M 期。'),
('ch12',['訊息傳遞特徵與受體類型'],P1,
 'The resting membrane potential of animal cells is established mainly by the Na⁺K⁺-ATPase, which for each ATP hydrolyzed moves:',
 ['3 Na⁺ out and 2 K⁺ in','2 Na⁺ out and 3 K⁺ in','3 Na⁺ in and 2 K⁺ out','1 Na⁺ out and 1 K⁺ in'],
 'A','每個 ATP：3 Na⁺ 出、2 K⁺ 進 → 細胞內為負（約 −50 到 −70 mV）。'),
# ---------------- Ch17 ----------------
('ch17',['β-oxidation 與 ATP 計算'],P1,
 'How many ATP are produced (net) from the complete oxidation of one stearate (18:0)? (NADH = 2.5, FADH2 = 1.5, acetyl-CoA = 10 ATP)',
 ['106','120','122','129'],
 'B','8 輪 β-oxidation：8 FADH₂ × 1.5 = 12、8 NADH × 2.5 = 20；9 acetyl-CoA × 10 = 90；共 122，扣活化 2 → 120。'),
('ch17',['Carnitine shuttle'],P0,
 'Which statement about the carnitine shuttle is FALSE?',
 ['Carnitine acyltransferase I is on the outer mitochondrial membrane','Malonyl-CoA inhibits carnitine acyltransferase I','Fatty acyl-CoA crosses the inner mitochondrial membrane directly','The translocase exchanges acyl-carnitine for free carnitine'],
 'C','Fatty acyl-CoA 不能穿過內膜，必須先轉成 acyl-carnitine。'),
('ch17',['酮體'],P1,
 'Which tissue cannot use ketone bodies as fuel?',
 ['Liver','Heart muscle','Brain during prolonged starvation','Renal cortex'],
 'A','肝臟沒有 β-ketoacyl-CoA transferase（thiophorase），只合成、不使用酮體。'),
('ch17',['奇數碳與 propionyl-CoA'],P1,
 'In vitamin B12 deficiency, which step in the metabolism of odd-chain fatty acids is impaired?',
 ['Propionyl-CoA carboxylase','Methylmalonyl-CoA epimerase','Methylmalonyl-CoA mutase','Thiolase'],
 'C','Methylmalonyl-CoA mutase 需要 coenzyme B₁₂（5′-deoxyadenosylcobalamin）；carboxylase 需要 biotin。'),
# ---------------- Ch21 ----------------
('ch21',['合成 vs 分解比較'],P0,
 'Which comparison between fatty acid synthesis and β-oxidation is FALSE?',
 ['Synthesis occurs in the cytosol; β-oxidation in the mitochondrial matrix','Synthesis uses NADPH; β-oxidation produces FADH2 and NADH','The acyl carrier in synthesis is ACP; in β-oxidation it is CoA','Both pathways use L-β-hydroxyacyl intermediates'],
 'D','合成的 β-hydroxyacyl 中間物是 D 型，β-oxidation 是 L 型。'),
('ch21',['脂肪酸合成與 ACC'],P1,
 'The rate-limiting enzyme of fatty acid synthesis and its allosteric activator are:',
 ['Acetyl-CoA carboxylase; citrate','Fatty acid synthase; palmitoyl-CoA','Citrate lyase; insulin','HMG-CoA reductase; mevalonate'],
 'A','ACC 是限速酶，citrate 別構活化（促進聚合）、palmitoyl-CoA 回饋抑制。'),
('ch21',['膽固醇合成與 HMG-CoA reductase'],P1,
 'Statins lower plasma LDL cholesterol mainly because they:',
 ['Block intestinal absorption of cholesterol','Competitively inhibit HMG-CoA reductase, lowering intracellular cholesterol and increasing LDL-receptor expression','Activate ACAT','Inhibit SREBP processing'],
 'B','細胞內膽固醇 ↓ → SREBP 活化 → LDL receptor ↑ → 肝臟從血中清除更多 LDL。'),
('ch21',['磷脂質合成'],P1,
 'In the liver, conversion of phosphatidylethanolamine to phosphatidylcholine uses which methyl donor?',
 ['N5-methyl-tetrahydrofolate','S-adenosylmethionine','Methylcobalamin','Biotin'],
 'B','PE 被 SAM 甲基化 3 次變成 PC。'),
# ---------------- Ch23 ----------------
('ch23',['胰島素與 GLUT'],P1,
 'Sulfonylurea drugs used in type 2 diabetes stimulate insulin release from β cells by:',
 ['Opening ATP-sensitive K⁺ channels','Closing ATP-sensitive K⁺ channels, depolarizing the membrane','Blocking voltage-gated Ca²⁺ channels','Increasing GLUT2 expression'],
 'B','與 ATP 的效果相同：關閉 K-ATP → 去極化 → 電壓門控 Ca²⁺ 通道打開 → Ca²⁺ 流入 → 胞吐。'),
('ch23',['各器官燃料代謝'],P1,
 'Muscle glycogen cannot be used to maintain blood glucose because muscle lacks:',
 ['Glycogen phosphorylase','Phosphoglucomutase','Glucose-6-phosphatase','Hexokinase'],
 'C','沒有 glucose-6-phosphatase，G6P 無法去磷酸化離開細胞，只能自己糖解。'),
('ch23',['飢餓與糖尿病','酮體'],P1,
 'After several weeks of starvation, which of the following is TRUE?',
 ['The brain obtains a large part of its energy from ketone bodies','Liver glycogen synthesis is increased','Plasma insulin is elevated','Fatty acids cross the blood–brain barrier to fuel the brain'],
 'A','長期飢餓時腦改用 β-hydroxybutyrate，減少糖質新生的需求、節省肌肉蛋白。脂肪酸過不了血腦障壁。'),
('ch23',['飢餓與糖尿病'],PC,
 'A 14-year-old with weight loss, polyuria, and fruity-smelling breath has very low plasma C-peptide. Which description fits best?',
 ['Type 2 diabetes caused by insulin resistance','Type 1 diabetes caused by autoimmune destruction of β cells','Excess leptin','Glucagon deficiency'],
 'B','C-peptide 低代表自身 insulin 分泌少；年輕、偏瘦、酮酸中毒（acetone 味）→ T1DM。'),
('ch23',['瘦素與脂肪激素'],P0,
 'Which statement about leptin is FALSE?',
 ['It is secreted by adipocytes','It is the product of the OB gene','It acts on the hypothalamus through a JAK-STAT pathway','Most obese individuals have abnormally low leptin levels'],
 'D','多數肥胖者 leptin 偏高，問題是 leptin resistance；只有少數 OB 基因缺陷者才缺 leptin。'),
('ch23',['AMPK／輔酶'],P1,
 'Activation of AMP-activated protein kinase (AMPK) in liver leads to:',
 ['Phosphorylation and inhibition of acetyl-CoA carboxylase','Activation of HMG-CoA reductase','Increased fatty acid synthesis','Inhibition of fatty acid oxidation'],
 'A','能量低時 AMPK 關掉耗能的合成（ACC、HMG-CoA reductase），malonyl-CoA ↓ → CPT I 解除抑制 → 脂肪酸氧化 ↑。'),
# ---------------- Ch18 ----------------
('ch18',['尿素循環'],P1,
 'The second nitrogen atom of urea is donated directly by:',
 ['Glutamate','Glutamine','Aspartate','Alanine'],
 'C','第一個 N 來自 NH₄⁺（carbamoyl phosphate），第二個由 aspartate 在 argininosuccinate synthetase 步驟加入。'),
('ch18',['尿素循環'],P1,
 'N-Acetylglutamate is an essential allosteric activator of:',
 ['Carbamoyl phosphate synthetase I','Ornithine transcarbamoylase','Arginase','Glutamate dehydrogenase'],
 'A','NAG 是 CPS I 的必需活化劑；NAG synthase 由 arginine 活化。'),
('ch18',['轉胺與 PLP'],P0,
 'Which reaction does NOT require pyridoxal phosphate?',
 ['Transamination of alanine','δ-Aminolevulinate synthase','Norepinephrine → epinephrine','DOPA → dopamine'],
 'C','Norepinephrine → epinephrine 是甲基化，甲基來自 SAM。'),
('ch18',['生酮／生醣胺基酸'],P1,
 'Which amino acids are exclusively ketogenic in humans?',
 ['Leucine and lysine','Isoleucine and threonine','Phenylalanine and tyrosine','Tryptophan and valine'],
 'A','只有 Leu、Lys 純生酮；Ile、Phe、Trp、Tyr、Thr 兩者皆是。'),
# ---------------- Ch22 ----------------
('ch22',['抗代謝藥物','Ribonucleotide reductase 與 dTMP'],P1,
 'Methotrexate blocks DNA synthesis in rapidly dividing cells by inhibiting:',
 ['Thymidylate synthase','Dihydrofolate reductase','Ribonucleotide reductase','Thymidine kinase'],
 'B','DHFR 被抑制 → THF 無法再生 → 沒有 methylene-THF 給 thymidylate synthase → dTMP 停止合成。'),
('ch22',['Salvage、Lesch-Nyhan 與 SCID'],P1,
 'In adenosine deaminase (ADA) deficiency, lymphocytes fail to proliferate because:',
 ['Uric acid accumulates in lymph nodes','dATP accumulates and inhibits ribonucleotide reductase','PRPP synthetase is inhibited','HGPRT is overactive'],
 'B','ADA 缺乏 → dATP 堆積 → 抑制 RNR → 無 dNTP 合成 DNA → SCID。'),
('ch22',['核苷酸分解與痛風'],P1,
 'Allopurinol lowers uric acid production because it:',
 ['Is a xanthine analog that activates uricase','Is a hypoxanthine analog that inhibits xanthine oxidase','Inhibits PRPP synthetase','Increases renal excretion of urate'],
 'B','Allopurinol 是 hypoxanthine 類似物，抑制 xanthine oxidase。'),
('ch22',['Salvage、Lesch-Nyhan 與 SCID'],PC,
 'A boy with hyperuricemia, choreoathetosis, and self-mutilating behavior most likely has a complete deficiency of:',
 ['Adenosine deaminase','HGPRT (hypoxanthine-guanine phosphoribosyltransferase)','Xanthine oxidase','Glucose-6-phosphatase'],
 'B','Lesch-Nyhan syndrome：HGPRT 完全缺乏、X-linked recessive；salvage 失效 → PRPP 堆積、purine 合成與尿酸大增。'),
]
out = []
for i, (ch, topics, pat, stem, opts, ans, ex) in enumerate(Q, 1):
    # 平衡答案分布：把選項循環平移，使正解落在 A→B→C→D 輪替的位置（數字題保持原順序）
    if not all(o.replace('.', '').isdigit() for o in opts):
        a = 'ABCD'.index(ans); want = (i - 1) % 4; shift = (a - want) % 4
        opts = opts[shift:] + opts[:shift]; ans = 'ABCD'[want]
    out.append(dict(id=f'new-{i:03d}', source='模擬新題', chapter=ch, type='mcq', stem=stem,
                    options=[dict(k='ABCD'[j], t=t) for j, t in enumerate(opts)],
                    answer=list(ans), explain=ex, topics=topics, pattern=pat))
json.dump(out, open(OUT, 'w'), ensure_ascii=False, indent=1)
open(OUT, 'a').write('\n')
import collections
print(len(out), collections.Counter(q['chapter'] for q in out))
